name: Deploy to Github Pages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Build
        run: npm install && npm run build
  deploy:
    environment:
      name: Deployment
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "./build"
      - name: Publish to github pages
        uses: actions/deploy-pages@v4
